language: android
sudo: required
jdk: oraclejdk8



before_cache:

 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/


before_install:
  - chmod +x gradlew
  
  
cache:

 directories:

 - $HOME/.gradle/caches/

 - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - TRAVIS_SECURE_ENV_VARS=true
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-26
#    - sys-img-armeabi-v7a-android-19



script:
- "./gradlew clean assembleRelease --stacktrace --daemon"